[project]
name = "mcp-nova-canvas"
version = "0.1.0"
description = "noval-canvas mcp server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.37.24",
    "httpx>=0.28.1",
    "mcp[cli]>=1.8.0",
    "pillow>=11.1.0",
    "uuid>=1.30",
    "loguru",
]
